version: 2
updates:
    - package-ecosystem: 'github-actions'
      directory: '/.github'
      commit-message:
          prefix: '[Github Actions]'
          include: 'scope'
      schedule:
          interval: 'weekly'
      assignees:
          - 'BennoDev'

    - package-ecosystem: 'npm'
      directory: '/'
      commit-message:
          prefix: '[Yarn]'
          include: 'scope'
      schedule:
          interval: 'weekly'
      groups:
          nx:
              patterns:
                  - '@nx/*'
                  - 'nx'
          nest:
              patterns:
                  - '@nestjs/*'
          mikro-orm:
              patterns:
                  - '@mikro-orm/*'
          eslint:
              patterns:
                  - '*eslint*'
                  - '*prettier*'
              exclude-patterns:
                  - '@nx/*'
          jest:
              patterns:
                  - '*jest*'
              exclude-patterns:
                  - '@nx/*'
          other:
              patterns:
                  - '*'
              exclude-patterns:
                  - '@nx/*'
                  - 'nx'
                  - '@nestjs/*'
                  - '@mikro-orm/*'
                  - '*eslint*'
                  - '*prettier*'
                  - '*jest*'
      ignore:
          - dependency-name: '@types/node'
      assignees:
          - 'BennoDev'
