version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/.github"
    commit-message:
      prefix: "[Github Actions]"
      include: "scope"
    schedule:
      interval: "weekly"
    assignees:
      - "BennoDev"

  - package-ecosystem: "yarn"
    directory: "/"
    commit-message:
      prefix: "[Yarn]"
      include: "scope"
    schedule:
      interval: "weekly"
    assignees:
      - "BennoDev"

  - package-ecosystem: "docker"
    directory: "/docker"
    commit-message:
      prefix: "[Docker]"
      include: "scope"
    schedule:
      interal: "weekly"
    assignees:
      - "BennoDev"
