apiVersion: 1

datasources:
    - name: Loki
      uid: loki
      type: loki
      url: http://loki:3100
    - name: Prometheus
      uid: prometheus
      type: prometheus
      url: http://prometheus:9090
    - name: Tempo
      uid: tempo
      type: tempo
      url: http://tempo:3200
      jsonData:
          tracesToLogsV2:
              datasourceUid: loki
