apiVersion: 1

datasources:
    - name: Loki
      type: loki
      url: http://loki:3100
    - name: Prometheus
      type: prometheus
      url: http://prometheus:9090
    - name: Tempo
      type: tempo
      url: http://tempo:3200
