receivers:
    otlp:
        protocols:
            grpc:
                endpoint: 0.0.0.0:4317
processors:
extensions:
    health_check: {}
exporters:
    otlp/tempo:
        endpoint: tempo:4317
        tls:
            insecure: true
    prometheusremotewrite:
        endpoint: http://prometheus:9090/api/v1/write
        tls:
            insecure: true
    otlphttp/loki:
        endpoint: http://loki:3100/otlp
        tls:
            insecure: true
service:
    pipelines:
        traces:
            receivers: [otlp]
            exporters: [otlp/tempo]
        metrics:
            receivers: [otlp]
            exporters: [prometheusremotewrite]
        logs:
            receivers: [otlp]
            exporters: [otlphttp/loki]
