receivers:
    otlp:
        protocols:
            grpc:
                endpoint: 0.0.0.0:4317
processors:
extensions:
    health_check: {}
exporters:
    otlp/tempo:
        endpoint: tempo:4317
        tls:
            insecure: true
    prometheus:
        endpoint: 0.0.0.0:9090
    otlphttp/loki:
        endpoint: http://loki:3100/otlp
        tls:
            insecure: true
service:
    pipelines:
        traces:
            receivers: [otlp]
            exporters: [otlp/tempo]
        metrics:
            receivers: [otlp]
            exporters: [prometheus]
        logs:
            receivers: [otlp]
            exporters: [otlphttp/loki]
