# https://medium.com/@blackhorseya/deploying-opentelemetry-collector-jaeger-and-prometheus-with-docker-compose-for-observability-fedd7c0898b5
# https://www.npmjs.com/package/@opentelemetry/auto-instrumentations-node
# https://github.com/open-telemetry/opentelemetry-collector/blob/main/receiver/README.md
# https://opentelemetry.io/docs/collector/configuration/
# https://hub.docker.com/r/grafana/grafana
# https://hub.docker.com/r/prom/prometheus
# https://grafana.com/docs/loki/latest/setup/install/docker/

# OTEL INSTRUMENTATION:
# Instrumentation needs to happen at the earliest possible point. Ideally before any framework / libraries are initialized.
# This is why we have a separate init.ts file for each service currently, but ideally you can export an /init file from a library or something and import that.
# If not instrumenting early, half of the instrumentations will not work at all.
#
# BULLMQ:
# Adding OTEL support to BullMQ is not difficult; you need to use the bullmq-otel package & BullMQOtel class.
# For NestJS, we are once again dealing with confusing BullMQ setup, as we have:
#  - forRoot(Async)
#  - registerQueue(Async)
#  - @Processor
# The place where you add this is important.
# For the PRODUCER, you CAN add it at the forRoot level - and MAYBE at the registerQueue level if you want to have multiple queues with different span names - which makes sense!
# For the CONSUMER, you MUST add it at the @Processor level. Any other place seems to have no effect whatsoever!
#
# DISTRIBUTED TRACING:
# For distributed tracing, you NEED to have propagation through a textMapPropagator!
# What the purpose of the SpanProcessor is - not entirely clear. Both with and without processor it works quite well :)
# Tracing with custom decorators, or via the { trace } import from @opentelemetry/api is straightforward and powerful.
#
# LOGGING: https://grafana.com/docs/loki/latest/send-data/otel/
# OTEL tracing makes own tracing solution redundant.
# HTTP OTEL exporter seems to be the best solution for logging, not sure why.
#
# GRAFANA LGMT:
# The LGTM stack is Loki, Grafana, Tempo & (Mimir/Prometheus) for logging, dashboard, tracing & metrics respectively.
# There is a comprehensive docker image that includes all of these and instruments with OTEL: https://hub.docker.com/r/grafana/otel-lgtm
#
# TODO:
# - Try Grafana Tempo
#   - Investigate trace to logs https://grafana.com/docs/grafana/latest/datasources/tempo/configure-tempo-data-source/#provision-the-data-source
# - Try getting application error monitoring in
# - Check out Grafana pyroscope: https://grafana.com/docs/pyroscope/latest/get-started/
#   - Investigate profiles to logs
# - Check out Grafana alloy instead of OTEL collector: https://grafana.com/docs/alloy/latest/set-up/install/docker/
# - Figure out Prometheus for NodeJS
#   - Investigate metrics to logs
# - Less important: check out Grafana Faro? https://github.com/grafana/faro-web-sdk/
# - Less important: check out Grafana Mimir? https://grafana.com/oss/mimir/

services:
    postgres:
        # Replace :latest with desired version when starting a new project
        image: postgres:latest
        ports:
            - 5432:5432
        env_file:
            - ./.env.postgres
    redis:
        # Replace :latest with desired version when starting a new project
        image: redis:latest
        ports:
            - 6379:6379

    otel-collector:
        image: otel/opentelemetry-collector:latest
        command: ['--config=/etc/otel-collector-config.yml']
        volumes:
            - ./config/otel-collector-config.yml:/etc/otel-collector-config.yml
        ports:
            - 4317:4317 # OTLP gRPC receiver

    # Check UI at http://localhost:9090
    prometheus:
        image: prom/prometheus:latest
        volumes:
            - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
        ports:
            - '9090:9090'

    tempo:
        image: grafana/tempo:latest
        command: ['-config.file=/etc/tempo/tempo-config.yml']
        ports:
            - 3200:3200
        volumes:
            - ./config/tempo-config.yml:/etc/tempo/tempo-config.yml
            - ./volumes/tempo:/var/tempo

    loki:
        image: grafana/loki:latest
        ports:
            - 3100:3100
            - 9096:9096
        volumes:
            - ./config/loki-config.yml:/etc/loki/loki-config.yaml

    # Check UI at http://localhost:3000
    grafana:
        image: grafana/grafana:latest
        ports:
            - 3000:3000
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=admin
        volumes:
            - ./volumes/grafana:/var/lib/grafana
            - ./config/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
