version: '3.8'
services:
    postgres:
        image: postgres:latest
        container_name: pgsql_${COMPOSE_PROJECT_NAME}
        ports:
            - 5432:5432
        env_file:
            - ./.env.postgres
        volumes:
            - ./volumes/postgres:/var/lib/postgresql/data
    redis:
        image: bitnami/redis:latest
        container_name: redis_${COMPOSE_PROJECT_NAME}
        ports:
            - 6379:6379
        env_file:
            - ./.env.redis
        volumes:
            - ./volumes/redis:/var/lib/redis/data
