name: main
on:
  push:
    branches:
      - main
  pull_request:
env:
  DATABASE_URL: postgres://developer:developer@localhost:5432/boilerplate
  DATABASE_SSL: false
jobs:
  main:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: developer
          POSTGRES_PASSWORD: developer
          POSTGRES_DB: boilerplate
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        env:
          REDIS_PASSWORD: developer
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
      - run: yarn install --immutable --immutable-cache --check-cache
      - uses: nrwl/nx-set-shas@v4
      - run: git branch --track main origin/main
      - run: yarn db:migrate
      - run: yarn db:seed
      - run: yarn nx format:check
      - run: yarn nx affected --target lint
      - run: yarn nx affected --target test
      - run: yarn nx affected --target build
