schema: 'https://schema.github.com/jobs'

name: main
on: [push]
jobs:
    main:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'yarn'
            - run: yarn install --immutable --immutable-cache --check-cache
            - uses: nrwl/nx-set-shas@v3
            - run: git branch --track main origin/main
            - run: yarn nx format:check
            - run: yarn nx affected --target lint
            - run: yarn nx affected --target test
            - run: yarn nx affected --target build
