name: main
on:
  pull_request:
env:
  DATABASE_URL: postgres://developer:developer@localhost:5432/boilerplate
  DATABASE_SSL: false
jobs:
  main:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: developer
          POSTGRES_PASSWORD: developer
          POSTGRES_DB: boilerplate
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install --immutable --immutable-cache --check-cache
      - name: Nx Set Shas
        uses: nrwl/nx-set-shas@v4
      - name: Track Main Branch
        run: git branch --track main origin/main
      - name: Run formatting
        run: yarn nx format:check
      - name: Run linting
        run: yarn nx affected --target lint
      - name: Migrate Database
        run: yarn db:migrate
      - name: Seed Database
        run: yarn db:seed
      - name: Run Tests
        run: yarn nx affected --target test
      - name: Building App
        run: yarn nx affected --target build
